{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8eecb26a",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (823308708.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"/tmp/ipykernel_3519/823308708.py\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    node {\u001b[0m\n\u001b[0m         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "node {\n",
    "  name: \"data\"\n",
    "  op: \"Placeholder\"\n",
    "  attr {\n",
    "    key: \"dtype\"\n",
    "    value {\n",
    "      type: DT_FLOAT\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"data_bn/FusedBatchNorm\"\n",
    "  op: \"FusedBatchNorm\"\n",
    "  input: \"data:0\"\n",
    "  input: \"data_bn/gamma\"\n",
    "  input: \"data_bn/beta\"\n",
    "  input: \"data_bn/mean\"\n",
    "  input: \"data_bn/std\"\n",
    "  attr {\n",
    "    key: \"epsilon\"\n",
    "    value {\n",
    "      f: 1.00099996416e-05\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"data_scale/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"data_bn/FusedBatchNorm\"\n",
    "  input: \"data_scale/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"data_scale/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"data_scale/Mul\"\n",
    "  input: \"data_scale/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"SpaceToBatchND/block_shape\"\n",
    "  op: \"Const\"\n",
    "  attr {\n",
    "    key: \"value\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_INT32\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "        }\n",
    "        int_val: 1\n",
    "        int_val: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"SpaceToBatchND/paddings\"\n",
    "  op: \"Const\"\n",
    "  attr {\n",
    "    key: \"value\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_INT32\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "        }\n",
    "        int_val: 3\n",
    "        int_val: 3\n",
    "        int_val: 3\n",
    "        int_val: 3\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"Pad\"\n",
    "  op: \"SpaceToBatchND\"\n",
    "  input: \"data_scale/BiasAdd\"\n",
    "  input: \"SpaceToBatchND/block_shape\"\n",
    "  input: \"SpaceToBatchND/paddings\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Pad\"\n",
    "  input: \"conv1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"VALID\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv1_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv1_h/Conv2D\"\n",
    "  input: \"conv1_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"BatchToSpaceND\"\n",
    "  op: \"BatchToSpaceND\"\n",
    "  input: \"conv1_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv1_bn_h/FusedBatchNorm\"\n",
    "  op: \"FusedBatchNorm\"\n",
    "  input: \"BatchToSpaceND\"\n",
    "  input: \"conv1_bn_h/gamma\"\n",
    "  input: \"conv1_bn_h/beta\"\n",
    "  input: \"conv1_bn_h/mean\"\n",
    "  input: \"conv1_bn_h/std\"\n",
    "  attr {\n",
    "    key: \"epsilon\"\n",
    "    value {\n",
    "      f: 1.00099996416e-05\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv1_scale_h/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"conv1_bn_h/FusedBatchNorm\"\n",
    "  input: \"conv1_scale_h/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv1_scale_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv1_scale_h/Mul\"\n",
    "  input: \"conv1_scale_h/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv1_scale_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv1_pool/MaxPool\"\n",
    "  op: \"MaxPool\"\n",
    "  input: \"Relu\"\n",
    "  attr {\n",
    "    key: \"ksize\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 3\n",
    "        i: 3\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_64_1_conv1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv1_pool/MaxPool\"\n",
    "  input: \"layer_64_1_conv1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_64_1_bn2_h/FusedBatchNorm\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_64_1_conv1_h/Conv2D\"\n",
    "  input: \"layer_64_1_conv1_h/Conv2D_bn_offset\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_64_1_scale2_h/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"layer_64_1_bn2_h/FusedBatchNorm\"\n",
    "  input: \"layer_64_1_scale2_h/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_64_1_scale2_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_64_1_scale2_h/Mul\"\n",
    "  input: \"layer_64_1_scale2_h/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_1\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_64_1_scale2_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_64_1_conv2_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_1\"\n",
    "  input: \"layer_64_1_conv2_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"add\"\n",
    "  op: \"Add\"\n",
    "  input: \"layer_64_1_conv2_h/Conv2D\"\n",
    "  input: \"conv1_pool/MaxPool\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_bn1_h/FusedBatchNorm\"\n",
    "  op: \"FusedBatchNorm\"\n",
    "  input: \"add\"\n",
    "  input: \"layer_128_1_bn1_h/gamma\"\n",
    "  input: \"layer_128_1_bn1_h/beta\"\n",
    "  input: \"layer_128_1_bn1_h/mean\"\n",
    "  input: \"layer_128_1_bn1_h/std\"\n",
    "  attr {\n",
    "    key: \"epsilon\"\n",
    "    value {\n",
    "      f: 1.00099996416e-05\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_scale1_h/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"layer_128_1_bn1_h/FusedBatchNorm\"\n",
    "  input: \"layer_128_1_scale1_h/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_scale1_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_128_1_scale1_h/Mul\"\n",
    "  input: \"layer_128_1_scale1_h/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_2\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_128_1_scale1_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_conv_expand_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_2\"\n",
    "  input: \"layer_128_1_conv_expand_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_conv1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_2\"\n",
    "  input: \"layer_128_1_conv1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_bn2/FusedBatchNorm\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_128_1_conv1_h/Conv2D\"\n",
    "  input: \"layer_128_1_conv1_h/Conv2D_bn_offset\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_scale2/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"layer_128_1_bn2/FusedBatchNorm\"\n",
    "  input: \"layer_128_1_scale2/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_scale2/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_128_1_scale2/Mul\"\n",
    "  input: \"layer_128_1_scale2/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_3\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_128_1_scale2/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_128_1_conv2/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_3\"\n",
    "  input: \"layer_128_1_conv2/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"add_1\"\n",
    "  op: \"Add\"\n",
    "  input: \"layer_128_1_conv2/Conv2D\"\n",
    "  input: \"layer_128_1_conv_expand_h/Conv2D\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_bn1/FusedBatchNorm\"\n",
    "  op: \"FusedBatchNorm\"\n",
    "  input: \"add_1\"\n",
    "  input: \"layer_256_1_bn1/gamma\"\n",
    "  input: \"layer_256_1_bn1/beta\"\n",
    "  input: \"layer_256_1_bn1/mean\"\n",
    "  input: \"layer_256_1_bn1/std\"\n",
    "  attr {\n",
    "    key: \"epsilon\"\n",
    "    value {\n",
    "      f: 1.00099996416e-05\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_scale1/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"layer_256_1_bn1/FusedBatchNorm\"\n",
    "  input: \"layer_256_1_scale1/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_scale1/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_256_1_scale1/Mul\"\n",
    "  input: \"layer_256_1_scale1/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_4\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_256_1_scale1/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"SpaceToBatchND_1/paddings\"\n",
    "  op: \"Const\"\n",
    "  attr {\n",
    "    key: \"value\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_INT32\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "        }\n",
    "        int_val: 1\n",
    "        int_val: 1\n",
    "        int_val: 1\n",
    "        int_val: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_conv_expand/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_4\"\n",
    "  input: \"layer_256_1_conv_expand/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv4_3_norm/l2_normalize\"\n",
    "  op: \"L2Normalize\"\n",
    "  input: \"Relu_4:0\"\n",
    "  input: \"conv4_3_norm/l2_normalize/Sum/reduction_indices\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv4_3_norm/mul_1\"\n",
    "  op: \"Mul\"\n",
    "  input: \"conv4_3_norm/l2_normalize\"\n",
    "  input: \"conv4_3_norm/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv4_3_norm_mbox_loc/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv4_3_norm/mul_1\"\n",
    "  input: \"conv4_3_norm_mbox_loc/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv4_3_norm_mbox_loc/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv4_3_norm_mbox_loc/Conv2D\"\n",
    "  input: \"conv4_3_norm_mbox_loc/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv4_3_norm_mbox_loc/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv4_3_norm_mbox_conf/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv4_3_norm/mul_1\"\n",
    "  input: \"conv4_3_norm_mbox_conf/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv4_3_norm_mbox_conf/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv4_3_norm_mbox_conf/Conv2D\"\n",
    "  input: \"conv4_3_norm_mbox_conf/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_6/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv4_3_norm_mbox_conf/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"Pad_1\"\n",
    "  op: \"SpaceToBatchND\"\n",
    "  input: \"Relu_4\"\n",
    "  input: \"SpaceToBatchND/block_shape\"\n",
    "  input: \"SpaceToBatchND_1/paddings\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_conv1/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Pad_1\"\n",
    "  input: \"layer_256_1_conv1/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"VALID\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_bn2/FusedBatchNorm\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_256_1_conv1/Conv2D\"\n",
    "  input: \"layer_256_1_conv1/Conv2D_bn_offset\"\n",
    "}\n",
    "node {\n",
    "  name: \"BatchToSpaceND_1\"\n",
    "  op: \"BatchToSpaceND\"\n",
    "  input: \"layer_256_1_bn2/FusedBatchNorm\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_scale2/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"BatchToSpaceND_1\"\n",
    "  input: \"layer_256_1_scale2/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_scale2/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_256_1_scale2/Mul\"\n",
    "  input: \"layer_256_1_scale2/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_5\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_256_1_scale2/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_256_1_conv2/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_5\"\n",
    "  input: \"layer_256_1_conv2/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"add_2\"\n",
    "  op: \"Add\"\n",
    "  input: \"layer_256_1_conv2/Conv2D\"\n",
    "  input: \"layer_256_1_conv_expand/Conv2D\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_bn1/FusedBatchNorm\"\n",
    "  op: \"FusedBatchNorm\"\n",
    "  input: \"add_2\"\n",
    "  input: \"layer_512_1_bn1/gamma\"\n",
    "  input: \"layer_512_1_bn1/beta\"\n",
    "  input: \"layer_512_1_bn1/mean\"\n",
    "  input: \"layer_512_1_bn1/std\"\n",
    "  attr {\n",
    "    key: \"epsilon\"\n",
    "    value {\n",
    "      f: 1.00099996416e-05\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_scale1/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"layer_512_1_bn1/FusedBatchNorm\"\n",
    "  input: \"layer_512_1_scale1/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_scale1/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_512_1_scale1/Mul\"\n",
    "  input: \"layer_512_1_scale1/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_6\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_512_1_scale1/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_conv_expand_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_6\"\n",
    "  input: \"layer_512_1_conv_expand_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_conv1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Relu_6\"\n",
    "  input: \"layer_512_1_conv1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_bn2_h/FusedBatchNorm\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_512_1_conv1_h/Conv2D\"\n",
    "  input: \"layer_512_1_conv1_h/Conv2D_bn_offset\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_scale2_h/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"layer_512_1_bn2_h/FusedBatchNorm\"\n",
    "  input: \"layer_512_1_scale2_h/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_scale2_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"layer_512_1_scale2_h/Mul\"\n",
    "  input: \"layer_512_1_scale2_h/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"Relu_7\"\n",
    "  op: \"Relu\"\n",
    "  input: \"layer_512_1_scale2_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_conv2_h/convolution/SpaceToBatchND\"\n",
    "  op: \"SpaceToBatchND\"\n",
    "  input: \"Relu_7\"\n",
    "  input: \"layer_512_1_conv2_h/convolution/SpaceToBatchND/block_shape\"\n",
    "  input: \"layer_512_1_conv2_h/convolution/SpaceToBatchND/paddings\"\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_conv2_h/convolution\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"layer_512_1_conv2_h/convolution/SpaceToBatchND\"\n",
    "  input: \"layer_512_1_conv2_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"VALID\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"layer_512_1_conv2_h/convolution/BatchToSpaceND\"\n",
    "  op: \"BatchToSpaceND\"\n",
    "  input: \"layer_512_1_conv2_h/convolution\"\n",
    "  input: \"layer_512_1_conv2_h/convolution/BatchToSpaceND/block_shape\"\n",
    "  input: \"layer_512_1_conv2_h/convolution/BatchToSpaceND/crops\"\n",
    "}\n",
    "node {\n",
    "  name: \"add_3\"\n",
    "  op: \"Add\"\n",
    "  input: \"layer_512_1_conv2_h/convolution/BatchToSpaceND\"\n",
    "  input: \"layer_512_1_conv_expand_h/Conv2D\"\n",
    "}\n",
    "node {\n",
    "  name: \"last_bn_h/FusedBatchNorm\"\n",
    "  op: \"FusedBatchNorm\"\n",
    "  input: \"add_3\"\n",
    "  input: \"last_bn_h/gamma\"\n",
    "  input: \"last_bn_h/beta\"\n",
    "  input: \"last_bn_h/mean\"\n",
    "  input: \"last_bn_h/std\"\n",
    "  attr {\n",
    "    key: \"epsilon\"\n",
    "    value {\n",
    "      f: 1.00099996416e-05\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"last_scale_h/Mul\"\n",
    "  op: \"Mul\"\n",
    "  input: \"last_bn_h/FusedBatchNorm\"\n",
    "  input: \"last_scale_h/mul\"\n",
    "}\n",
    "node {\n",
    "  name: \"last_scale_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"last_scale_h/Mul\"\n",
    "  input: \"last_scale_h/add\"\n",
    "}\n",
    "node {\n",
    "  name: \"last_relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"last_scale_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"last_relu\"\n",
    "  input: \"conv6_1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_1_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv6_1_h/Conv2D\"\n",
    "  input: \"conv6_1_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_1_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv6_1_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv6_1_h/Relu\"\n",
    "  input: \"conv6_2_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv6_2_h/Conv2D\"\n",
    "  input: \"conv6_2_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv6_2_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv6_2_h/Relu\"\n",
    "  input: \"conv7_1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_1_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv7_1_h/Conv2D\"\n",
    "  input: \"conv7_1_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_1_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv7_1_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"Pad_2\"\n",
    "  op: \"SpaceToBatchND\"\n",
    "  input: \"conv7_1_h/Relu\"\n",
    "  input: \"SpaceToBatchND/block_shape\"\n",
    "  input: \"SpaceToBatchND_1/paddings\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"Pad_2\"\n",
    "  input: \"conv7_2_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"VALID\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 2\n",
    "        i: 2\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv7_2_h/Conv2D\"\n",
    "  input: \"conv7_2_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"BatchToSpaceND_2\"\n",
    "  op: \"BatchToSpaceND\"\n",
    "  input: \"conv7_2_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"BatchToSpaceND_2\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv7_2_h/Relu\"\n",
    "  input: \"conv8_1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_1_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv8_1_h/Conv2D\"\n",
    "  input: \"conv8_1_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_1_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv8_1_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv8_1_h/Relu\"\n",
    "  input: \"conv8_2_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv8_2_h/Conv2D\"\n",
    "  input: \"conv8_2_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv8_2_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_1_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv8_2_h/Relu\"\n",
    "  input: \"conv9_1_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_1_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv9_1_h/Conv2D\"\n",
    "  input: \"conv9_1_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_1_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv9_1_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_h/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv9_1_h/Relu\"\n",
    "  input: \"conv9_2_h/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_h/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv9_2_h/Conv2D\"\n",
    "  input: \"conv9_2_h/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_h/Relu\"\n",
    "  op: \"Relu\"\n",
    "  input: \"conv9_2_h/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_mbox_loc/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv9_2_h/Relu\"\n",
    "  input: \"conv9_2_mbox_loc/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_mbox_loc/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv9_2_mbox_loc/Conv2D\"\n",
    "  input: \"conv9_2_mbox_loc/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_5/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv9_2_mbox_loc/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_mbox_conf/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv9_2_h/Relu\"\n",
    "  input: \"conv9_2_mbox_conf/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv9_2_mbox_conf/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv9_2_mbox_conf/Conv2D\"\n",
    "  input: \"conv9_2_mbox_conf/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_11/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv9_2_mbox_conf/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_mbox_loc/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv8_2_h/Relu\"\n",
    "  input: \"conv8_2_mbox_loc/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_mbox_loc/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv8_2_mbox_loc/Conv2D\"\n",
    "  input: \"conv8_2_mbox_loc/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_4/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv8_2_mbox_loc/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_mbox_conf/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv8_2_h/Relu\"\n",
    "  input: \"conv8_2_mbox_conf/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv8_2_mbox_conf/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv8_2_mbox_conf/Conv2D\"\n",
    "  input: \"conv8_2_mbox_conf/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_10/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv8_2_mbox_conf/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_mbox_loc/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv7_2_h/Relu\"\n",
    "  input: \"conv7_2_mbox_loc/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_mbox_loc/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv7_2_mbox_loc/Conv2D\"\n",
    "  input: \"conv7_2_mbox_loc/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_3/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv7_2_mbox_loc/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_mbox_conf/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv7_2_h/Relu\"\n",
    "  input: \"conv7_2_mbox_conf/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv7_2_mbox_conf/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv7_2_mbox_conf/Conv2D\"\n",
    "  input: \"conv7_2_mbox_conf/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_9/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv7_2_mbox_conf/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_mbox_loc/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv6_2_h/Relu\"\n",
    "  input: \"conv6_2_mbox_loc/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_mbox_loc/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv6_2_mbox_loc/Conv2D\"\n",
    "  input: \"conv6_2_mbox_loc/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_2/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv6_2_mbox_loc/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_mbox_conf/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"conv6_2_h/Relu\"\n",
    "  input: \"conv6_2_mbox_conf/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"conv6_2_mbox_conf/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"conv6_2_mbox_conf/Conv2D\"\n",
    "  input: \"conv6_2_mbox_conf/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_8/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"conv6_2_mbox_conf/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"fc7_mbox_loc/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"last_relu\"\n",
    "  input: \"fc7_mbox_loc/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"fc7_mbox_loc/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"fc7_mbox_loc/Conv2D\"\n",
    "  input: \"fc7_mbox_loc/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_1/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"fc7_mbox_loc/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"mbox_loc\"\n",
    "  op: \"ConcatV2\"\n",
    "  input: \"flatten/Reshape\"\n",
    "  input: \"flatten_1/Reshape\"\n",
    "  input: \"flatten_2/Reshape\"\n",
    "  input: \"flatten_3/Reshape\"\n",
    "  input: \"flatten_4/Reshape\"\n",
    "  input: \"flatten_5/Reshape\"\n",
    "  input: \"mbox_loc/axis\"\n",
    "}\n",
    "node {\n",
    "  name: \"fc7_mbox_conf/Conv2D\"\n",
    "  op: \"Conv2D\"\n",
    "  input: \"last_relu\"\n",
    "  input: \"fc7_mbox_conf/weights\"\n",
    "  attr {\n",
    "    key: \"dilations\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"padding\"\n",
    "    value {\n",
    "      s: \"SAME\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"strides\"\n",
    "    value {\n",
    "      list {\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "        i: 1\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"fc7_mbox_conf/BiasAdd\"\n",
    "  op: \"BiasAdd\"\n",
    "  input: \"fc7_mbox_conf/Conv2D\"\n",
    "  input: \"fc7_mbox_conf/bias\"\n",
    "}\n",
    "node {\n",
    "  name: \"flatten_7/Reshape\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"fc7_mbox_conf/BiasAdd\"\n",
    "}\n",
    "node {\n",
    "  name: \"mbox_conf\"\n",
    "  op: \"ConcatV2\"\n",
    "  input: \"flatten_6/Reshape\"\n",
    "  input: \"flatten_7/Reshape\"\n",
    "  input: \"flatten_8/Reshape\"\n",
    "  input: \"flatten_9/Reshape\"\n",
    "  input: \"flatten_10/Reshape\"\n",
    "  input: \"flatten_11/Reshape\"\n",
    "  input: \"mbox_conf/axis\"\n",
    "}\n",
    "node {\n",
    "  name: \"mbox_conf_reshape\"\n",
    "  op: \"Reshape\"\n",
    "  input: \"mbox_conf\"\n",
    "  input: \"reshape_before_softmax\"\n",
    "}\n",
    "node {\n",
    "  name: \"mbox_conf_softmax\"\n",
    "  op: \"Softmax\"\n",
    "  input: \"mbox_conf_reshape\"\n",
    "  attr {\n",
    "    key: \"axis\"\n",
    "    value {\n",
    "      i: 2\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"mbox_conf_flatten\"\n",
    "  op: \"Flatten\"\n",
    "  input: \"mbox_conf_softmax\"\n",
    "}\n",
    "node {\n",
    "  name: \"PriorBox_0\"\n",
    "  op: \"PriorBox\"\n",
    "  input: \"conv4_3_norm/mul_1\"\n",
    "  input: \"data\"\n",
    "  attr {\n",
    "    key: \"aspect_ratio\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 1\n",
    "          }\n",
    "        }\n",
    "        float_val: 2.0\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"clip\"\n",
    "    value {\n",
    "      b: false\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"flip\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"max_size\"\n",
    "    value {\n",
    "      i: 60\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"min_size\"\n",
    "    value {\n",
    "      i: 30\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"offset\"\n",
    "    value {\n",
    "      f: 0.5\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"step\"\n",
    "    value {\n",
    "      f: 8.0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"variance\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 4\n",
    "          }\n",
    "        }\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.20000000298\n",
    "        float_val: 0.20000000298\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"PriorBox_1\"\n",
    "  op: \"PriorBox\"\n",
    "  input: \"last_relu\"\n",
    "  input: \"data\"\n",
    "  attr {\n",
    "    key: \"aspect_ratio\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "        }\n",
    "        float_val: 2.0\n",
    "        float_val: 3.0\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"clip\"\n",
    "    value {\n",
    "      b: false\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"flip\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"max_size\"\n",
    "    value {\n",
    "      i: 111\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"min_size\"\n",
    "    value {\n",
    "      i: 60\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"offset\"\n",
    "    value {\n",
    "      f: 0.5\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"step\"\n",
    "    value {\n",
    "      f: 16.0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"variance\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 4\n",
    "          }\n",
    "        }\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.20000000298\n",
    "        float_val: 0.20000000298\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"PriorBox_2\"\n",
    "  op: \"PriorBox\"\n",
    "  input: \"conv6_2_h/Relu\"\n",
    "  input: \"data\"\n",
    "  attr {\n",
    "    key: \"aspect_ratio\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "        }\n",
    "        float_val: 2.0\n",
    "        float_val: 3.0\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"clip\"\n",
    "    value {\n",
    "      b: false\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"flip\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"max_size\"\n",
    "    value {\n",
    "      i: 162\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"min_size\"\n",
    "    value {\n",
    "      i: 111\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"offset\"\n",
    "    value {\n",
    "      f: 0.5\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"step\"\n",
    "    value {\n",
    "      f: 32.0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"variance\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 4\n",
    "          }\n",
    "        }\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.20000000298\n",
    "        float_val: 0.20000000298\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"PriorBox_3\"\n",
    "  op: \"PriorBox\"\n",
    "  input: \"conv7_2_h/Relu\"\n",
    "  input: \"data\"\n",
    "  attr {\n",
    "    key: \"aspect_ratio\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 2\n",
    "          }\n",
    "        }\n",
    "        float_val: 2.0\n",
    "        float_val: 3.0\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"clip\"\n",
    "    value {\n",
    "      b: false\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"flip\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"max_size\"\n",
    "    value {\n",
    "      i: 213\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"min_size\"\n",
    "    value {\n",
    "      i: 162\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"offset\"\n",
    "    value {\n",
    "      f: 0.5\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"step\"\n",
    "    value {\n",
    "      f: 64.0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"variance\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 4\n",
    "          }\n",
    "        }\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.20000000298\n",
    "        float_val: 0.20000000298\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"PriorBox_4\"\n",
    "  op: \"PriorBox\"\n",
    "  input: \"conv8_2_h/Relu\"\n",
    "  input: \"data\"\n",
    "  attr {\n",
    "    key: \"aspect_ratio\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 1\n",
    "          }\n",
    "        }\n",
    "        float_val: 2.0\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"clip\"\n",
    "    value {\n",
    "      b: false\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"flip\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"max_size\"\n",
    "    value {\n",
    "      i: 264\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"min_size\"\n",
    "    value {\n",
    "      i: 213\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"offset\"\n",
    "    value {\n",
    "      f: 0.5\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"step\"\n",
    "    value {\n",
    "      f: 100.0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"variance\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 4\n",
    "          }\n",
    "        }\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.20000000298\n",
    "        float_val: 0.20000000298\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"PriorBox_5\"\n",
    "  op: \"PriorBox\"\n",
    "  input: \"conv9_2_h/Relu\"\n",
    "  input: \"data\"\n",
    "  attr {\n",
    "    key: \"aspect_ratio\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 1\n",
    "          }\n",
    "        }\n",
    "        float_val: 2.0\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"clip\"\n",
    "    value {\n",
    "      b: false\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"flip\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"max_size\"\n",
    "    value {\n",
    "      i: 315\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"min_size\"\n",
    "    value {\n",
    "      i: 264\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"offset\"\n",
    "    value {\n",
    "      f: 0.5\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"step\"\n",
    "    value {\n",
    "      f: 300.0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"variance\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_FLOAT\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 4\n",
    "          }\n",
    "        }\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.10000000149\n",
    "        float_val: 0.20000000298\n",
    "        float_val: 0.20000000298\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"mbox_priorbox\"\n",
    "  op: \"ConcatV2\"\n",
    "  input: \"PriorBox_0\"\n",
    "  input: \"PriorBox_1\"\n",
    "  input: \"PriorBox_2\"\n",
    "  input: \"PriorBox_3\"\n",
    "  input: \"PriorBox_4\"\n",
    "  input: \"PriorBox_5\"\n",
    "  input: \"mbox_loc/axis\"\n",
    "}\n",
    "node {\n",
    "  name: \"detection_out\"\n",
    "  op: \"DetectionOutput\"\n",
    "  input: \"mbox_loc\"\n",
    "  input: \"mbox_conf_flatten\"\n",
    "  input: \"mbox_priorbox\"\n",
    "  attr {\n",
    "    key: \"background_label_id\"\n",
    "    value {\n",
    "      i: 0\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"code_type\"\n",
    "    value {\n",
    "      s: \"CENTER_SIZE\"\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"confidence_threshold\"\n",
    "    value {\n",
    "      f: 0.00999999977648\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"keep_top_k\"\n",
    "    value {\n",
    "      i: 200\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"nms_threshold\"\n",
    "    value {\n",
    "      f: 0.449999988079\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"num_classes\"\n",
    "    value {\n",
    "      i: 2\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"share_location\"\n",
    "    value {\n",
    "      b: true\n",
    "    }\n",
    "  }\n",
    "  attr {\n",
    "    key: \"top_k\"\n",
    "    value {\n",
    "      i: 400\n",
    "    }\n",
    "  }\n",
    "}\n",
    "node {\n",
    "  name: \"reshape_before_softmax\"\n",
    "  op: \"Const\"\n",
    "  attr {\n",
    "    key: \"value\"\n",
    "    value {\n",
    "      tensor {\n",
    "        dtype: DT_INT32\n",
    "        tensor_shape {\n",
    "          dim {\n",
    "            size: 3\n",
    "          }\n",
    "        }\n",
    "        int_val: 0\n",
    "        int_val: -1\n",
    "        int_val: 2\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "library {\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "808fc588",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
